name = "Bakhtiar Rifai"
avatar = "images/profilku.webp?width=32px&height=32px" # Avatar image. Default to "images/profile.webp".
bio = "Belajar sepanjang Hayat"
company = "SMAN 2 Wates"
location = "Indonesia"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"

[social]
  email = "user@domain.tld"
  facebook = "yourfacebookusername"
  github = "yourgithubusername"
  twitter = "yourtwitterusername"
  linkedin = "yourlinkedinusername"